services:
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    restart: unless-stopped
    depends_on:
       db:
        condition: service_healthy # Espera a que el healthcheck de bd sea exitoso
    ports:
      - "${PRESTASHOP_PORT}:80"
    environment:
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
    volumes: # Para la persistencia de datos
      - psdata:/var/www/html
    networks:
      - prestashop_network

  db:
    container_name: mysql
    image: mysql:8.0.43
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
    - prestashop_network
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy # Espera a que el healthcheck de bd sea exitoso
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_ARBITRARY: ${PMA_ARBITRARY}
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - prestashop_network

volumes: # Para la persistencia de datos
  dbdata:
  psdata:

networks:
  prestashop_network: